name: GitHub Actions Demo
run-name: build and test the project
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ master,  microfrontends ]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        node-version: [ 22.x, 25.x]
    steps:
      - uses: actions/checkout@v4
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: npm install
      - name: typecheck
        run: npm run typecheck
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - run: echo "This job's status is ${{ job.status }}."
